---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 1h
  releaseName: grafana
  targetNamespace: apps
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      version: 7.3.11
  values:
    installCRDs: true
