---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bitnami-charts.yaml
  - ./prometheus-community-charts.yaml
  - ./jetstack-charts.yaml
  - ./grafana-charts.yaml
  - ./enix-charts.yaml
  - ./shanestarcher-charts.yaml
