---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helm-exporter
  namespace: monitoring
spec:
  releaseName: helm-exporter
  interval: 1m
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  chart:
    spec:
      chart: helm-exporter
      version: 1.2.12
      sourceRef:
        kind: HelmRepository
        name: shanestarcher-charts
        namespace: flux-system
  values:
    intervalDuration: 1h
    latestChartVersion: false
    resources:
      requests:
        cpu: 1m
        memory: 64Mi
        ephemeral-storage: 10Mi
      limits:
        cpu: 200m
        memory: 256Mi
        ephemeral-storage: 100Mi
    serviceMonitor:
      interval: 30m
      create: true
