---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config
  namespace: flux-system
spec:
  interval: 30m
  timeout: 5m
  retryInterval: 1m
  dependsOn:
    - name: flux-system
  path: ./kubernetes/clusters/${ENVIRONMENT}/config
  prune: true
  force: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
